name: 'Update Vcpkg Repository'
description: 'Clones and creates appropriate changes in a vcpkg repository'
inputs:
  remote-vcpkg-repository:
    description: 'The remote vcpkg github repository url'
    required: true
runs:
  using: 'docker'
  image: 'Dockerfile'
  args:
    - -r ${{ inputs.remote-vcpkg-repository }} -c ./clone